# Generated by Django 2.1.5 on 2019-01-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
