# Generated by Django 2.1.4 on 2019-01-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190102_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='name',
            field=models.CharField(max_length=68),
        ),
    ]
